# Generated by Django 6.0.1 on 2026-01-15 00:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image_url", models.URLField()),
                ("description", models.TextField()),
                ("capacity", models.IntegerField()),
                ("signed_up_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
