# Generated by Django 6.0.1 on 2026-01-15 07:38

import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image_url",
        ),
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=django_mongodb_backend.fields.ObjectIdAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
