services:
  - type: web
    name: campus-events-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn example.wsgi --log-file -"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Matches runtime.txt
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_NAME
        sync: false
